### Get all elements 
GET http://localhost:5050/life-hacks

### Get one element by its id 
GET http://localhost:5050/life-hacks/67df9912478d5cd7f25681de

### Creates a new element
POST http://localhost:5050/life-hacks
Content-Type: application/json

{
  "title": "Your title here",
  "content": "Your content here"
}

### Updated an existing element
PUT http://localhost:5050/life-hacks/67e0de7079b5c6f9db6bbf9d
Content-Type: application/json

{
  "title": "This is an update test",
  "content": "This element has been successfully updated"
}

### Deletes one element by its id 
DELETE http://localhost:5050/life-hacks/67e0de8f79b5c6f9db6bbf9e